import java.security.SecureRandom;
import java.util.*;

public class Multiplay3 {

    SecureRandom randomNumber = new SecureRandom();
    Scanner input = new Scanner(System.in);

    private  static final int row = 100;
    private  static final int column = 5;
    private final int[][] questions = new int[row][column];

    private int number1;
    private int number2;
    private int totalQuestions = 0;
    private int totalCorrectQuestions = 0;

    public void quiz()
    {
        int userInput;

        createQuestion();
        userInput = input.nextInt();

        while(userInput != -1)
        {
            checkResponse(userInput);
            userInput = input.nextInt();
        }

    }

    public void createQuestion()
    {

        number1 = randomNumber.nextInt(10);
        number2 = randomNumber.nextInt(10);

        System.out.printf("How much is %d times %d?%n", number1,number2);
        System.out.println("Enter your answer (-1 to exit):");
    }

    public String createResponse(boolean check)
    {
        final String[] wrongResponse = {"No. Please try again.", "Don't give up!",
                "Wrong. Try once more.", "No. Keep trying."};

        final String[] correctResponse = {"Very good!", "Excellent!",
                "Keep up the good work!", "Nice work!"};


        int num = randomNumber.nextInt(4);

        if(check)
        {
            return correctResponse[num];
        }
        else
        {
            return wrongResponse[num];
        }

    }

    public void checkResponse(int inputAnswer)
    {
        int answer = number1 * number2; // correct answer
        questions[totalQuestions][0] = number1;
        questions[totalQuestions][1] = number2;
        questions[totalQuestions][2] = answer;
        questions[totalQuestions][3] = inputAnswer;


        if(inputAnswer != answer)
        {
            System.out.printf("%s%n",createResponse(false));
            System.out.printf("The correct answer is %d.%n%n",questions[totalQuestions][2]);
        }
        else
        {
            totalCorrectQuestions++;
            System.out.printf("%s%n",createResponse(true));
        }

        totalQuestions++;
        createQuestion();
    }

    public void printQuestionResult()
    {
        System.out.println("The questions generated by the system are:");
        for(int i = 0; i < totalQuestions; i++)
        {
            if(questions[i][2] == questions[i][3])
            {
                System.out.printf("%d * %d = %d%n",questions[i][0],
                        questions[i][1],questions[i][2]);
            }
            else
            {
                System.out.printf("%d * %d = %d Your answer was %d, which is incorrect.%n",
                        questions[i][0], questions[i][1],questions[i][2],questions[i][3]);
            }
        }

        System.out.println("---------------------------------------------------------------\n");
        System.out.printf("You got %d questions and made %d question correct.%n",
                totalQuestions, totalCorrectQuestions);

        double rate =  totalCorrectQuestions / (double)totalQuestions;
        if (rate > 0.6)
        {
            System.out.printf("%s%n",createResponse(true));
        }
        else
            System.out.printf("%s%n",createResponse(false));
    }

}
